//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIBRARYEntities : DbContext
    {
        public LIBRARYEntities()
            : base("name=LIBRARYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABOUT_BOOK> ABOUT_BOOK { get; set; }
        public virtual DbSet<ABOUT_READER> ABOUT_READER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
