//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUT_BOOK
    {
        public string BOOK_AUTHOR { get; set; }
        public string NAME_OF_BOOK { get; set; }
        public System.DateTime YEAR_OF_PUBLICATION { get; set; }
        public decimal PRICE { get; set; }
        public int NUMBER_OF_COPIES { get; set; }
        public string SHORT_ANNOTATION { get; set; }
    }
}
