//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUT_READER
    {
        public int LIBRARY_CARD_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string ADDRESS { get; set; }
        public System.DateTime DATE_OF_ISSUE { get; set; }
        public System.DateTime DATE_OF_PASS { get; set; }
        public Nullable<System.TimeSpan> TIME_OF_LEAVE { get; set; }
    }
}
