CREATE DATABASE [LIBRARY]
USE [LIBRARY]
GO

CREATE TABLE ABOUT_BOOK (
[BOOK_AUTHOR]           NVARCHAR(MAX) NOT NULL,
[NAME_OF_BOOK]          NVARCHAR PRIMARY KEY NOT NULL,
[YEAR_OF_PUBLICATION]	DATE NOT NULL,
[PRICE]					MONEY NOT NULL,
[NUMBER_OF_COPIES]		INT NOT NULL,
[SHORT_ANNOTATION]		NVARCHAR(MAX) NOT NULL
)
GO

CREATE TABLE ABOUT_READER(
[LIBRARY_CARD_ID]		INT PRIMARY KEY NOT NULL,
[FULL_NAME]				NVARCHAR(MAX) NOT NULL,
[ADDRESS]				NVARCHAR(MAX) NOT NULL,
[DATE_OF_ISSUE]			DATE NOT NULL,
[DATE_OF_PASS]			DATE NOT NULL,
[TIME_OF_LEAVE]			TIME
)
GO

drop table ABOUT_BOOK, ABOUT_READER

